function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(3)=(params(8)*(params(4)*(1-exo_(2)))^params(1)*(params(3)*(1-exo_(1)))^(1-params(1))/(1/params(2)-(1-params(6))))^(1/(1-params(8)));
    ys_(2)=(params(4)*(1-exo_(2)))^params(1)*(params(3)*(1-exo_(1)))^(1-params(1))*ys_(3)^params(8);
    ys_(1)=ys_(2)-params(6)*ys_(3);
    ys_(4)=ys_(2)-ys_(1);
    ys_(5)=(params(4)*(1-exo_(2)))^params(1)*(params(3)*(1-exo_(1)))^(1-params(1));
    % Auxiliary equations
end
